#!/bin/sh

EXPECTED_ARGS=1
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` {path}"
  exit $E_BADARGS
fi

REPOSITORY=$1

SCRIPT=$(readlink -f ${BASH_SOURCE[0]})
SCRIPT_PATH=$(dirname $(readlink -f ${BASH_SOURCE[0]}))

mkdir -p $REPOSITORY
cd $REPOSITORY
git init

touch README
git echo "Drupal Website Deployer Repository (subtree merge strategy), scriptified scratchbuild" > README
cp $SCRIPT ./scratchbuild
cp ${SCRIPT_PATH}/add-remotes ./add-remotes
git add README scratchbuild add-remotes

git commit -m "Initial Commit"

# Create workflow branches
git branch drupal
git branch patches
git branch devel
git branch site-data
git branch host-config
git branch deploy

git checkout drupal

# Add all remotes and fetch tags as necessary
./add-remotes

# Merge Drupal v6.19 under drupal-6.x
git merge -s ours --no-commit 88146f6d
git read-tree --prefix=drupal-6.x/ -u 88146f6d
git commit -m "Merge of drupal-6.19"

# Merge Drupal v7.0 under drupal-7.x
git merge -s ours --no-commit 49791492
git read-tree --prefix=drupal-7.x/ -u 49791492
git commit -m "Merge of drupal-7.0"

# Add all modules
mkdir -p drupal-6.x/sites/all/modules

git merge -s ours --no-commit 18eb12b8d83767d3497942475e0290901c1ef008
git read-tree --prefix=drupal-6.x/sites/all/modules/admin_menu/ -u 18eb12b8d83767d3497942475e0290901c1ef008
git commit -m "Merge of admin_menu"


git merge -s ours --no-commit 775335f1fa68a4bf05c1ca8d8fd0e544c56383a6
git read-tree --prefix=drupal-6.x/sites/all/modules/advanced_help/ -u  775335f1fa68a4bf05c1ca8d8fd0e544c56383a6
git commit -m "Merge of advanced_help"


git merge -s ours --no-commit dc8728fbec694fd32697692192996af5200ea3e7
git read-tree --prefix=drupal-6.x/sites/all/modules/amazon/ -u  dc8728fbec694fd32697692192996af5200ea3e7
git commit -m "Merge of amazon"


git merge -s ours --no-commit da30c2a180372fba7ed821592fbd5e63528c4a67
git read-tree --prefix=drupal-6.x/sites/all/modules/arrange_fields/ -u  da30c2a180372fba7ed821592fbd5e63528c4a67
git commit -m "Merge of arrange_fields"


git merge -s ours --no-commit be75c14defe982ff455fe2ece968927b7502c4e1
git read-tree --prefix=drupal-6.x/sites/all/modules/autoload/ -u  be75c14defe982ff455fe2ece968927b7502c4e1
git commit -m "Merge of autoload"


git merge -s ours --no-commit b1db6e6e8124f780c6423c8844a10d9c18174853
git read-tree --prefix=drupal-6.x/sites/all/modules/auto_nodetitle/ -u  b1db6e6e8124f780c6423c8844a10d9c18174853
git commit -m "Merge of auto_nodetitle"


git merge -s ours --no-commit 5d44332bc62388b17e3f75990aa4bf22c028c6dd
git read-tree --prefix=drupal-6.x/sites/all/modules/cck/ -u  5d44332bc62388b17e3f75990aa4bf22c028c6dd
git commit -m "Merge of cck"


git merge -s ours --no-commit e9ffaeb0d9c0e80d079ed26131938e75d58ee405
git read-tree --prefix=drupal-6.x/sites/all/modules/cck_fieldgroup_tabs/ -u  e9ffaeb0d9c0e80d079ed26131938e75d58ee405
git commit -m "Merge of cck_fieldgroup_tabs"


git merge -s ours --no-commit cfdf6e65583127c1694b31b51c482fcb4518f7c7
git read-tree --prefix=drupal-6.x/sites/all/modules/codefilter/ -u  cfdf6e65583127c1694b31b51c482fcb4518f7c7
git commit -m "Merge of codefilter"


git merge -s ours --no-commit 9eb528cc652045ae7253d0863ec88c4a2043dd66
git read-tree --prefix=drupal-6.x/sites/all/modules/comment_upload/ -u  9eb528cc652045ae7253d0863ec88c4a2043dd66
git commit -m "Merge of comment_upload"


git merge -s ours --no-commit a8b5ec3249fc918171704f31ee48558605a929b5
git read-tree --prefix=drupal-6.x/sites/all/modules/computed_field/ -u  a8b5ec3249fc918171704f31ee48558605a929b5
git commit -m "Merge of computed_field"


git merge -s ours --no-commit 28aba335c4c56ea589110cf1430ddef54f43bc4f
git read-tree --prefix=drupal-6.x/sites/all/modules/ctools/ -u  28aba335c4c56ea589110cf1430ddef54f43bc4f
git commit -m "Merge of ctools"


git merge -s ours --no-commit f0c443ca4dab3e894b73b58c5ea8e74a95a89cee
git read-tree --prefix=drupal-6.x/sites/all/modules/currency/ -u  f0c443ca4dab3e894b73b58c5ea8e74a95a89cee
git commit -m "Merge of currency"


git merge -s ours --no-commit ff56ee79f0a66aea1578aedf95447e922333f5bc
git read-tree --prefix=drupal-6.x/sites/all/modules/devel/ -u  ff56ee79f0a66aea1578aedf95447e922333f5bc
git commit -m "Merge of devel"


git merge -s ours --no-commit d28193a7500d518a1fe939d17b5df585fcfc743d
git read-tree --prefix=drupal-6.x/sites/all/modules/drupalforfirebug/ -u  d28193a7500d518a1fe939d17b5df585fcfc743d
git commit -m "Merge of drupalforfirebug"


git merge -s ours --no-commit 7a97dfe78bbbff800dbf5eed647c6b9c6fd83a17
git read-tree --prefix=drupal-6.x/sites/all/modules/elements/ -u  7a97dfe78bbbff800dbf5eed647c6b9c6fd83a17
git commit -m "Merge of elements"


git merge -s ours --no-commit e162f8d2d478c6c4b7e05d274ee853f042856c7c
git read-tree --prefix=drupal-6.x/sites/all/modules/faq/ -u  e162f8d2d478c6c4b7e05d274ee853f042856c7c
git commit -m "Merge of faq"


git merge -s ours --no-commit a473473f7257628c4428e9e4ffa4de55b91f8adf
git read-tree --prefix=drupal-6.x/sites/all/modules/fbconnect/ -u  a473473f7257628c4428e9e4ffa4de55b91f8adf
git commit -m "Merge of fbconnect"

git merge -s ours --no-commit b14edfa34306e3f112d73fd72e73cf72f473c3d5
git read-tree --prefix=drupal-6.x/sites/all/modules/fbconnect/facebook-php-sdk/ -u b14edfa34306e3f112d73fd72e73cf72f473c3d5
git commit -m "Merge of facebook-php-sdk"

git merge -s ours --no-commit 65f2f71f6a5223ad7ed00795aff6971cc3926c8e
git read-tree --prefix=drupal-6.x/sites/all/modules/fckeditor/ -u  65f2f71f6a5223ad7ed00795aff6971cc3926c8e
git commit -m "Merge of fckeditor"


git merge -s ours --no-commit d3fcc8abb75e9223e1a1ae2b50fd484809c8d876
git read-tree --prefix=drupal-6.x/sites/all/modules/feedback/ -u  d3fcc8abb75e9223e1a1ae2b50fd484809c8d876
git commit -m "Merge of feedback"


git merge -s ours --no-commit 1c0d56d3627f5a562ca3d77a6ea1a963f44580b6
git read-tree --prefix=drupal-6.x/sites/all/modules/file_aliases/ -u  1c0d56d3627f5a562ca3d77a6ea1a963f44580b6
git commit -m "Merge of file_aliases"


git merge -s ours --no-commit 317c8ec0d33ce544b8fb0d47443a2b0910423964
git read-tree --prefix=drupal-6.x/sites/all/modules/filefield/ -u  317c8ec0d33ce544b8fb0d47443a2b0910423964
git commit -m "Merge of filefield"


git merge -s ours --no-commit f3cf8f2e09b76b6c96c1d4c4440b6503e629afe2
git read-tree --prefix=drupal-6.x/sites/all/modules/filefield_paths/ -u  f3cf8f2e09b76b6c96c1d4c4440b6503e629afe2
git commit -m "Merge of filefield_paths"


git merge -s ours --no-commit edd55a13e8b339135118e7aa2cf544db991540c7
git read-tree --prefix=drupal-6.x/sites/all/modules/flickr/ -u  edd55a13e8b339135118e7aa2cf544db991540c7
git commit -m "Merge of flickr"


git merge -s ours --no-commit d1702e3fb6b4d67c387ab60806fe86c35c6a70e6
git read-tree --prefix=drupal-6.x/sites/all/modules/format_number/ -u  d1702e3fb6b4d67c387ab60806fe86c35c6a70e6
git commit -m "Merge of format_number"


git merge -s ours --no-commit 45c3e97be052acbed077ff2bda9e7f72de2a89f6
git read-tree --prefix=drupal-6.x/sites/all/modules/formatted_number/ -u  45c3e97be052acbed077ff2bda9e7f72de2a89f6
git commit -m "Merge of formatted_number"


git merge -s ours --no-commit b1d1926fe703f88156b57b477d7c341bf85fd1ac
git read-tree --prefix=drupal-6.x/sites/all/modules/globalredirect/ -u  b1d1926fe703f88156b57b477d7c341bf85fd1ac
git commit -m "Merge of globalredirect"


git merge -s ours --no-commit bfe2bdd3b7b29f83ef278aca48de5712460ad5eb
git read-tree --prefix=drupal-6.x/sites/all/modules/google_analytics/ -u  bfe2bdd3b7b29f83ef278aca48de5712460ad5eb
git commit -m "Merge of google_analytics"


git merge -s ours --no-commit 30d9cdac5cd2883f2c64748946cfcc1fa38791b5
git read-tree --prefix=drupal-6.x/sites/all/modules/htmlpurifier/ -u  30d9cdac5cd2883f2c64748946cfcc1fa38791b5
git commit -m "Merge of htmlpurifier"

git checkout patches
merge drupal
git merge -s ours --no-commit 18e538317a877a0509ae71a860429c41770da230
git read-tree --prefix=drupal-6.x/sites/all/modules/htmlpurifier/library/ -u 213dfe955bb7ca84d8874d7fcebdaf5ed2bb5853
git commit -m "Merge of htmlpurifier/library"

git checkout drupal
git merge -s ours --no-commit d900d7f90711c5f00b6d6b0a388559d03c87b28a
git read-tree --prefix=drupal-6.x/sites/all/modules/image/ -u  d900d7f90711c5f00b6d6b0a388559d03c87b28a
git commit -m "Merge of image"


git merge -s ours --no-commit d92f61af372ee82f6d8077acff34d0edf60b0147
git read-tree --prefix=drupal-6.x/sites/all/modules/imageapi/ -u  d92f61af372ee82f6d8077acff34d0edf60b0147
git commit -m "Merge of imageapi"


git merge -s ours --no-commit afb9715c2de1e8f7388f0e5cc4123dbe81848685
git read-tree --prefix=drupal-6.x/sites/all/modules/imagefield/ -u  afb9715c2de1e8f7388f0e5cc4123dbe81848685
git commit -m "Merge of imagefield"


git merge -s ours --no-commit 0418532bd9e5c827db312fdca5b1a20fe4b809ab
git read-tree --prefix=drupal-6.x/sites/all/modules/imagefield_tokens/ -u  0418532bd9e5c827db312fdca5b1a20fe4b809ab
git commit -m "Merge of imagefield_tokens"


git merge -s ours --no-commit 224bb3d5724d677ef81795f851a4f118cc4d8283
git read-tree --prefix=drupal-6.x/sites/all/modules/inputstream/ -u  224bb3d5724d677ef81795f851a4f118cc4d8283
git commit -m "Merge of inputstream"


git merge -s ours --no-commit a51a5ab234e0b0544574c122ef9df9471b5ffe92
git read-tree --prefix=drupal-6.x/sites/all/modules/jquery_ui/ -u  a51a5ab234e0b0544574c122ef9df9471b5ffe92
git commit -m "Merge of jquery_ui"


git merge -s ours --no-commit 528210e98290a4d771b4f4bbd8e6191946fcd8cd
git read-tree --prefix=drupal-6.x/sites/all/modules/json_server/ -u  528210e98290a4d771b4f4bbd8e6191946fcd8cd
git commit -m "Merge of json_server"


git merge -s ours --no-commit bba5c8a52eb3a3f508e1613e0f6fa0d993a3a176
git read-tree --prefix=drupal-6.x/sites/all/modules/link/ -u  bba5c8a52eb3a3f508e1613e0f6fa0d993a3a176
git commit -m "Merge of link"


git merge -s ours --no-commit 1f32e758b7f7acc015c7b6cfa11cc91544891214
git read-tree --prefix=drupal-6.x/sites/all/modules/logintoboggan/ -u  1f32e758b7f7acc015c7b6cfa11cc91544891214
git commit -m "Merge of logintoboggan"


git merge -s ours --no-commit ca9db254b785887fee344ad65970b4c1d25e40c2
git read-tree --prefix=drupal-6.x/sites/all/modules/mimedetect/ -u  ca9db254b785887fee344ad65970b4c1d25e40c2
git commit -m "Merge of mimedetect"


git merge -s ours --no-commit ef7c9b1860b9a7799ab3df50c9b840ece8c14162
git read-tree --prefix=drupal-6.x/sites/all/modules/mollom/ -u  ef7c9b1860b9a7799ab3df50c9b840ece8c14162
git commit -m "Merge of mollom"


git merge -s ours --no-commit 361c8de57a69f66216512c65c219e6345bc2571d
git read-tree --prefix=drupal-6.x/sites/all/modules/mvf/ -u  361c8de57a69f66216512c65c219e6345bc2571d
git commit -m "Merge of mvf"


git merge -s ours --no-commit d3aa52fbfe170d04395283f11758c3d5d2b1ea38
git read-tree --prefix=drupal-6.x/sites/all/modules/node_export/ -u  d3aa52fbfe170d04395283f11758c3d5d2b1ea38
git commit -m "Merge of node_export"


git merge -s ours --no-commit 0d65a9782d35bd702de80d6fbd345f81d41d8743
git read-tree --prefix=drupal-6.x/sites/all/modules/nodereference_views/ -u  0d65a9782d35bd702de80d6fbd345f81d41d8743
git commit -m "Merge of nodereference_views"


git merge -s ours --no-commit be9d41a3a0eb6639276d57b83fccbf7f2a1d04ea
git read-tree --prefix=drupal-6.x/sites/all/modules/nodereference_views_select/ -u be9d41a3a0eb6639276d57b83fccbf7f2a1d04ea
git commit -m "Merge of nodereference_views_select"


git merge -s ours --no-commit c8ba5261dbb3ae6237aa036725fca9ad62842e7f
git read-tree --prefix=drupal-6.x/sites/all/modules/page_title/ -u  c8ba5261dbb3ae6237aa036725fca9ad62842e7f
git commit -m "Merge of page_title"


git merge -s ours --no-commit f1064ff1cb4079132ce080ffba43bbba8ea6a324
git read-tree --prefix=drupal-6.x/sites/all/modules/panels/ -u  f1064ff1cb4079132ce080ffba43bbba8ea6a324
git commit -m "Merge of panels"


git merge -s ours --no-commit f01db87c0355dc5ea5102043c5b73f3aabfad0b6
git read-tree --prefix=drupal-6.x/sites/all/modules/panels_tabs/ -u  f01db87c0355dc5ea5102043c5b73f3aabfad0b6
git commit -m "Merge of panels_tabs"


git merge -s ours --no-commit acf1ccea484056cd54e80039fdc14d3ca9ee3384
git read-tree --prefix=drupal-6.x/sites/all/modules/pathauto/ -u  acf1ccea484056cd54e80039fdc14d3ca9ee3384
git commit -m "Merge of pathauto"


git merge -s ours --no-commit 66a3c6505d91249ea07254c35d4dd48796119fd2
git read-tree --prefix=drupal-6.x/sites/all/modules/path_redirect/ -u 66a3c6505d91249ea07254c35d4dd48796119fd2
git commit -m "Merge of path_redirect"


git merge -s ours --no-commit 03e4cec0dfafedef6ad7b8d0acaa5acb8bb9c669
git read-tree --prefix=drupal-6.x/sites/all/modules/pingback/ -u 03e4cec0dfafedef6ad7b8d0acaa5acb8bb9c669
git commit -m "Merge of pingback"


git merge -s ours --no-commit f1d67eacd064474877e03975fddc26d950af3f52
git read-tree --prefix=drupal-6.x/sites/all/modules/project/ -u f1d67eacd064474877e03975fddc26d950af3f52
git commit -m "Merge of project"


git merge -s ours --no-commit b474cda1b54fa509d31ae018e638aeafda36b1f6
git read-tree --prefix=drupal-6.x/sites/all/modules/project_issue/ -u b474cda1b54fa509d31ae018e638aeafda36b1f6
git commit -m "Merge of project_issue"


git merge -s ours --no-commit a67247d0dda6ac0b681052bbb9936985cf7f68cc
git read-tree --prefix=drupal-6.x/sites/all/modules/recipe/ -u a67247d0dda6ac0b681052bbb9936985cf7f68cc
git commit -m "Merge of recipe"


git merge -s ours --no-commit 9a4b882c22fcec93ac5c59147dd3af59e80d4aa9
git read-tree --prefix=drupal-6.x/sites/all/modules/rest_server/ -u 9a4b882c22fcec93ac5c59147dd3af59e80d4aa9
git commit -m "Merge of rest_server"


git merge -s ours --no-commit 3e2844e33cf58a8bd995cfc85abda26ce54a04dc
git read-tree --prefix=drupal-6.x/sites/all/modules/robotstxt/ -u 3e2844e33cf58a8bd995cfc85abda26ce54a04dc
git commit -m "Merge of robotstxt"


git merge -s ours --no-commit 388afc11147cb7bb84d39e0662fcffd44ac6cfa5
git read-tree --prefix=drupal-6.x/sites/all/modules/search_files/ -u 388afc11147cb7bb84d39e0662fcffd44ac6cfa5
git commit -m "Merge of search_files"


git merge -s ours --no-commit 85f989c9b20084f0eaa33b863544f04f8ab30d0f
git read-tree --prefix=drupal-6.x/sites/all/modules/seo_checklist/ -u 85f989c9b20084f0eaa33b863544f04f8ab30d0f
git commit -m "Merge of seo_checklist"


git merge -s ours --no-commit c753db8a408ad82b20cf15b444feabddc0620fc7
git read-tree --prefix=drupal-6.x/sites/all/modules/services/ -u c753db8a408ad82b20cf15b444feabddc0620fc7
git commit -m "Merge of services"


git merge -s ours --no-commit 898124aead6042aed7f829c8fedf32752366696c
git read-tree --prefix=drupal-6.x/sites/all/modules/site_verify/ -u 898124aead6042aed7f829c8fedf32752366696c
git commit -m "Merge of site_verify"


git merge -s ours --no-commit be09f99a16832bfcc18f0372a1d04833b3f31dc1
git read-tree --prefix=drupal-6.x/sites/all/modules/tablefield/ -u be09f99a16832bfcc18f0372a1d04833b3f31dc1
git commit -m "Merge of tablefield"


git merge -s ours --no-commit 204e807eca8ed11510caf3b30720833902065541
git read-tree --prefix=drupal-6.x/sites/all/modules/tabs/ -u 204e807eca8ed11510caf3b30720833902065541
git commit -m "Merge of tabs"


git merge -s ours --no-commit 309726cec4112b42b2b3d14f0c292e448491883a
git read-tree --prefix=drupal-6.x/sites/all/modules/taxonomy_manager/ -u 309726cec4112b42b2b3d14f0c292e448491883a
git commit -m "Merge of taxonomy_manager"


git merge -s ours --no-commit f68bc4dbcd43e8a0e03976c862bafddd5c5f1bd7
git read-tree --prefix=drupal-6.x/sites/all/modules/textformatter/ -u f68bc4dbcd43e8a0e03976c862bafddd5c5f1bd7
git commit -m "Merge of textformatter"


git merge -s ours --no-commit 5ba1c3930e33ec643095f65973ca4dfddf5b6e5e
git read-tree --prefix=drupal-6.x/sites/all/modules/text_noderef/ -u 5ba1c3930e33ec643095f65973ca4dfddf5b6e5e
git commit -m "Merge of text_noderef"


git merge -s ours --no-commit c7d877c1b1e4f0d7b66430226a74dfefa33d7290
git read-tree --prefix=drupal-6.x/sites/all/modules/token/ -u c7d877c1b1e4f0d7b66430226a74dfefa33d7290
git commit -m "Merge of token"


git merge -s ours --no-commit b43db0347a236dd76550f4444f6dc664d34c671d
git read-tree --prefix=drupal-6.x/sites/all/modules/transliteration/ -u b43db0347a236dd76550f4444f6dc664d34c671d
git commit -m "Merge of transliteration"


git merge -s ours --no-commit 017d72796de9835974c25ccfbee3e3aa70049a46
git read-tree --prefix=drupal-6.x/sites/all/modules/units/ -u 017d72796de9835974c25ccfbee3e3aa70049a46
git commit -m "Merge of units"


git merge -s ours --no-commit b8f2874a81e0a173cb76265d033dbabe779f5f07
git read-tree --prefix=drupal-6.x/sites/all/modules/unitsapi/ -u b8f2874a81e0a173cb76265d033dbabe779f5f07
git commit -m "Merge of unitsapi"


git merge -s ours --no-commit d5ee0092aca9677ec3eeacf9cd8b864668b371b3
git read-tree --prefix=drupal-6.x/sites/all/modules/user_register_notify/ -u d5ee0092aca9677ec3eeacf9cd8b864668b371b3fy
git commit -m "Merge of user_register_notify"


git merge -s ours --no-commit 28b4ff175ee69bff2452abb225d247aa3ab3a4fd
git read-tree --prefix=drupal-6.x/sites/all/modules/viewreference/ -u 28b4ff175ee69bff2452abb225d247aa3ab3a4fd
git commit -m "Merge of viewreference"


git merge -s ours --no-commit 429d3608a94b0a2436c7cd60062ecc8d36e67061
git read-tree --prefix=drupal-6.x/sites/all/modules/views/ -u 429d3608a94b0a2436c7cd60062ecc8d36e67061
git commit -m "Merge of views"


git merge -s ours --no-commit 15d618fbeee1257d0795f5245e03a9c9f96b0b42
git read-tree --prefix=drupal-6.x/sites/all/modules/viewsdisplaytabs/ -u 15d618fbeee1257d0795f5245e03a9c9f96b0b42
git commit -m "Merge of viewsdisplaytabs"


git merge -s ours --no-commit b30b54cb7c9573ce44d306e4fdbc149242f17f0d
git read-tree --prefix=drupal-6.x/sites/all/modules/views_rss/ -u b30b54cb7c9573ce44d306e4fdbc149242f17f0d
git commit -m "Merge of views_rss"


git merge -s ours --no-commit b59c80e3352a5d7f4d1b28a8894362a30bc88ed6
git read-tree --prefix=drupal-6.x/sites/all/modules/webform/ -u b59c80e3352a5d7f4d1b28a8894362a30bc88ed6
git commit -m "Merge of webform"


git merge -s ours --no-commit 70ffd85ffe879daa101d631a858ec7f1cd841d53
git read-tree --prefix=drupal-6.x/sites/all/modules/xmlsitemap/ -u 70ffd85ffe879daa101d631a858ec7f1cd841d53
git commit -m "Merge of xmlsitemap"

#git checkout mangle
#cp -r ~/filezilla/modules/dev/onthisdate drupal-6.x/sites/all/modules
#git commit -am "dave's module tutorial work"
